
# Site settings
name: eacabbi.github.io
title: Edoardo Maria Acabbi
description: Assistant Professor of Economics at the University of Mannheim.
repo: https://github.com/ildodo12/website
url: https://eacabbi.github.io
baseurl: /eacabbi.github.io
google_analytics: UA-179129314-1
google-site-verification: EjDn9NB75Ybc73Rp6H3LzGkSFajoB4_PGmSHZUPYT3o

# Personal info
author: Edoardo Maria Acabbi
first_name: Edoardo Maria
last_name: Acabbi
university: University of Mannheim
department: Economics Department
address: L 7. 3-5, P001, 68161, Mannheim, Germany
office: 
email: edoardo.maria.acabbi@uni-mannheim.de
university2: Northwestern University
department2: Economics Department
address2: 2211 Campus Dr, 60208 Evanston IL, USA
office2: KGH 3439
email2: eacabbi@northwestern.edu

# Icon settings
doi_icon: ai ai-doi
doi_title: DOI
data_icon: ai ai-open-data
data_title: Data
pdf_icon: fas fa-file-pdf
pdf_title: PDF
course_icon: fas fa-info-circle
course_title: Info
moodle_icon: ai ai-moodle-square
moodle_title: Moodle
link_icon: fas fa-external-link-square-alt
link_title: Link

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
